-- MySQL Script generated by MySQL Workbench
-- Thu Jun 12 23:32:04 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Arquivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Arquivo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Arquivo` (
  `idArquivo` INT NOT NULL,
  `url` TEXT(200) NULL,
  `nome_arquivo` VARCHAR(45) NULL,
  `tipo_arquivo` ENUM('PDF', 'IMG') NULL,
  `fk_idConteudo` INT NOT NULL,
  PRIMARY KEY (`idArquivo`, `fk_idConteudo`),
  CONSTRAINT `fk_Arquivo_Conteudo1`
    FOREIGN KEY (`fk_idConteudo`)
    REFERENCES `mydb`.`Conteudo` (`idConteudo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Arquivo_Conteudo1_idx` ON `mydb`.`Arquivo` (`fk_idConteudo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `idCategoria` INT NOT NULL,
  `categoria` VARCHAR(45) NULL,
  `descricao` TEXT(200) NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Checklist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Checklist` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Checklist` (
  `idChecklist` INT NOT NULL,
  `descricao_checklist` TEXT(100) NULL,
  `concluido` TINYINT NULL,
  `fk_idConteudo` INT NOT NULL,
  `Ordem` INT NULL,
  PRIMARY KEY (`idChecklist`, `fk_idConteudo`),
  CONSTRAINT `fk_Checklist_Conteudo1`
    FOREIGN KEY (`fk_idConteudo`)
    REFERENCES `mydb`.`Conteudo` (`idConteudo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Checklist_Conteudo1_idx` ON `mydb`.`Checklist` (`fk_idConteudo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Conteudo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Conteudo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Conteudo` (
  `idConteudo` INT NOT NULL,
  `tipo` ENUM('video', 'resumo', 'exercicio', 'outro') NULL,
  `titulo_conteudo` VARCHAR(45) NULL,
  `link` TEXT(200) NULL,
  `observacao` TEXT(100) NULL,
  `fk_idTopico` INT NOT NULL,
  `prioridade` ENUM('baixa', 'média', 'alta') NULL,
  PRIMARY KEY (`idConteudo`, `fk_idTopico`),
  CONSTRAINT `fk_Conteudo_Topico1`
    FOREIGN KEY (`fk_idTopico`)
    REFERENCES `mydb`.`Topico` (`idTopico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Conteudo_Topico1_idx` ON `mydb`.`Conteudo` (`fk_idTopico` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Estudo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Estudo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Estudo` (
  `idEstudo` INT NOT NULL,
  `data_criacao` DATETIME NULL,
  `duracao_minutos` INT NULL,
  `observacoes_estudo` TEXT(100) NULL,
  `fk_idusuario` INT NOT NULL,
  `fk_idConteudo` INT NOT NULL,
  `data_fim_estudo` DATETIME NULL,
  PRIMARY KEY (`idEstudo`, `fk_idusuario`, `fk_idConteudo`),
  CONSTRAINT `fk_Estudo_Usuario1`
    FOREIGN KEY (`fk_idusuario`)
    REFERENCES `mydb`.`Usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudo_Conteudo1`
    FOREIGN KEY (`fk_idConteudo`)
    REFERENCES `mydb`.`Conteudo` (`idConteudo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Estudo_Usuario1_idx` ON `mydb`.`Estudo` (`fk_idusuario` ASC) VISIBLE;

CREATE INDEX `fk_Estudo_Conteudo1_idx` ON `mydb`.`Estudo` (`fk_idConteudo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Integracao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Integracao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Integracao` (
  `idIntegracao` INT NOT NULL,
  `plataforma` ENUM('Notion', 'GoogleCalendar', 'Trello') NULL,
  `token` TEXT(200) NULL,
  `fk_idusuario` INT NOT NULL,
  PRIMARY KEY (`idIntegracao`, `fk_idusuario`),
  CONSTRAINT `fk_Integracao_Usuario1`
    FOREIGN KEY (`fk_idusuario`)
    REFERENCES `mydb`.`Usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Integracao_Usuario1_idx` ON `mydb`.`Integracao` (`fk_idusuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Materia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Materia` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Materia` (
  `idMateria` INT NOT NULL,
  `nome_materia` VARCHAR(45) NULL,
  `fk_idusuario` INT NOT NULL,
  `fk_idCategoria` INT NOT NULL,
  PRIMARY KEY (`idMateria`, `fk_idusuario`, `fk_idCategoria`),
  CONSTRAINT `fk_Materia_Usuario`
    FOREIGN KEY (`fk_idusuario`)
    REFERENCES `mydb`.`Usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Materia_Categoria1`
    FOREIGN KEY (`fk_idCategoria`)
    REFERENCES `mydb`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Materia_Usuario_idx` ON `mydb`.`Materia` (`fk_idusuario` ASC) VISIBLE;

CREATE INDEX `fk_Materia_Categoria1_idx` ON `mydb`.`Materia` (`fk_idCategoria` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Notificacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Notificacao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Notificacao` (
  `idNotificacao` INT NOT NULL,
  `mensagem` TEXT(100) NULL,
  `tipo_notificacao` VARCHAR(45) NULL,
  `data_envio` DATETIME NULL,
  `status_notificacao` TINYINT NULL,
  `fk_idRevisao` INT NOT NULL,
  `fk_idusuario` INT NOT NULL,
  PRIMARY KEY (`idNotificacao`, `fk_idRevisao`, `fk_idusuario`),
  CONSTRAINT `fk_Notificacao_Revisao1`
    FOREIGN KEY (`fk_idRevisao`)
    REFERENCES `mydb`.`Revisao` (`idRevisao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notificacao_Usuario1`
    FOREIGN KEY (`fk_idusuario`)
    REFERENCES `mydb`.`Usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Notificacao_Revisao1_idx` ON `mydb`.`Notificacao` (`fk_idRevisao` ASC) VISIBLE;

CREATE INDEX `fk_Notificacao_Usuario1_idx` ON `mydb`.`Notificacao` (`fk_idusuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Planejamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Planejamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Planejamento` (
  `idPlanejamento` INT NOT NULL,
  `data_planejada` DATETIME NULL,
  `meta` TEXT(100) NULL,
  `fk_idusuario` INT NOT NULL,
  PRIMARY KEY (`idPlanejamento`, `fk_idusuario`),
  CONSTRAINT `fk_Planejamento_Usuario1`
    FOREIGN KEY (`fk_idusuario`)
    REFERENCES `mydb`.`Usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Planejamento_Usuario1_idx` ON `mydb`.`Planejamento` (`fk_idusuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Revisao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Revisao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Revisao` (
  `idRevisao` INT NOT NULL,
  `data_revisao` DATETIME NULL,
  `status` TINYINT NULL,
  `observacao_revisao` TEXT(200) NULL,
  `tipo_revisao` ENUM('7 dias', '15 dias', '30 dais') NULL,
  `criado_em` DATETIME NULL,
  `fk_idusuario` INT NOT NULL,
  PRIMARY KEY (`idRevisao`, `fk_idusuario`),
  CONSTRAINT `fk_Revisao_Usuario1`
    FOREIGN KEY (`fk_idusuario`)
    REFERENCES `mydb`.`Usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Revisao_Usuario1_idx` ON `mydb`.`Revisao` (`fk_idusuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Topico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Topico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Topico` (
  `idTopico` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `descricao_topico` TEXT(80) NULL,
  `fk_idMateria` INT NOT NULL,
  PRIMARY KEY (`idTopico`, `fk_idMateria`),
  CONSTRAINT `fk_Topico_Materia1`
    FOREIGN KEY (`fk_idMateria`)
    REFERENCES `mydb`.`Materia` (`idMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Topico_Materia1_idx` ON `mydb`.`Topico` (`fk_idMateria` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idusuario` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `senha_hash` VARCHAR(45) NULL,
  `data_criacao` DATETIME NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `email_UNIQUE` ON `mydb`.`Usuario` (`email` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
